version: '3.4'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: ghcr.io/kb-group-enterprise/menuler-frontend:dev 
#define network
networks:
  default:
    external:
      name: capstone-dev
